config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/signin', to: 'sessions#new', as: 'signin'
  post '/sessions', to: "sessions#create"
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/users/signup', to:'users#new', as:'signup'
  post '/users', to: 'users#create'
  get '/users/:id', to:'users#show', as:'user'
  get '/', to:'sessions#show'
  # get '/albums', to:'albums#index', as:'all_albums'
  post '/comments', to: 'comments#create'
  get '/albums/:id/delete', to: 'albums#destroy'
  get '/auth/facebook/callback' => 'sessions#create'
  resources :albums do 
    resources :comments
    resources :galaxies, only: [:index, :new]
  
    resources :space_objs, only: [:index, :new]
    
    resources :planets, only: [:index, :new]
  end

  resources :galaxies, only: [:show, :create] 
  
  resources :space_objs, only: [:show, :create]

  resources :planets, only: [:show, :create]

end

app/models/album.rb
class Album < ApplicationRecord
    validates :title, presence: true
    validates :date, presence: true
    validates :description, presence: true
    validates :href, presence: true
    
    belongs_to :author
    has_many :comments
    has_many :users, through: :comments
    has_many :album_planets 
    has_many :album_space_objs
    has_many :album_galaxies
    has_many :galaxies, through: :album_galaxies
    has_many :space_objs, through: :album_space_objs
    has_many :planets, through: :album_planets
    
    def self.new_albums
        @api = Api.new
        @items = @api.fetch("")
        if !@items.nil?
            @all_items = @items["collection"]["items"]
            Api.new_from_hash(@all_items, false)
        end
    end

    def self.search_albums(search)
        @api = Api.new       
        @items = @api.fetch("#{search}")
        if !@items.nil?
            @all_items = @items["collection"]["items"]
            Api.new_from_hash(@all_items, true)
        end
    end

    def self.filter_albums(filter)
        if filter[:option] == 'Most Popular'
           sorted_albums = Album.most_popular
       elsif filter[:option] == 'Newest'
           sorted_albums = Album.newest
       elsif filter[:option] == 'Oldest'
           sorted_albums = Album.oldest
       else
           return Album.all
       end
       return sorted_albums
   end

   def self.most_popular
        return Album.all.order('comments_count DESC')
   end

   def self.newest
        return Album.all.order('created_at DESC')
   end

   def self.oldest
        return Album.all.order('created_at ASC')
   end

   def galaxies_attributes=(galaxies_attributes)
    attr_status = check_if_attr_empty(galaxies_attributes)
    if attr_status == true
      galaxies_attributes.values.each do |galaxies_attribute|
        galaxy = Galaxy.find_or_create_by(galaxies_attribute)
        self.galaxies << galaxy
      end
    end
  end

  def planets_attributes=(planets_attributes)
    attr_status = check_if_attr_empty(planets_attributes)
    if attr_status == true
      planets_attributes.values.each do |planets_attribute|
        planet = Planet.find_or_create_by(planets_attribute)
        self.planets << planet
      end
    end
  end

  def space_objs_attributes=(space_objs_attributes)
    attr_status = check_if_attr_empty(space_objs_attributes)
    if attr_status == true
      space_objs_attributes.values.each do |space_objs_attribute|
        space_obj = SpaceObj.find_or_create_by(space_objs_attribute)
        self.space_objs << space_obj
      end
    end
  end

  def check_if_attr_empty(attributes)
    return true if attributes[:name] != "" && attributes[:picture_src]
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    before_action :require_login 

    def index
        @filters = ["Most Popular", "Newest", "Oldest"]
        if params.include?(:search)
            Album.search_albums(params[:search])
            @albums = search_user_albums(params[:search])
            if @albums.nil? || @albums.empty?
                flash[:alert] = "Sorry Nothing matches that search"
            end
        else
            @albums = Album.all.order('created_at DESC').uniq(&:title)
        end
        if params.include?(:filter)
            @albums = Album.filter_albums(params[:filter])
        end

    end

    def show
        @album = Album.find_by(id: params[:id])
        @comments = Comment.sort_time(@album.comments)
        @comment = Comment.new
        @galaxies = @album.galaxies.uniq(&:name)
        @space_objs = @album.space_objs.uniq(&:name)
        @planets = @album.planets.uniq(&:name)
        if @album.nil?
            redirect_to all_albums_path
        end
    end

    def new
        @album = Album.new
    end

    def create
        @album = Album.new(album_params)
        @author = Author.find_by(:id => album_params[:author_id])
        @album.author = @author
        if @album.save
            redirect_to album_path(@album)
        else
            render 'new'
        end
    end

    def edit
        @album = Album.find_by(:id => params[:id])
    end

    def update
        @album = Album.find_by(:id => params[:id])
        @album.update(album_params)
        if @album.save
            redirect_to album_path(@album)
        else            
            render 'edit'
        end
    end

    def destroy
        # raise params.inspect
        @album = Album.find_by(:id => params[:id])
        if @album.user != current_user 
            redirect_to user_path(current_user)
        else
            @album.destroy
            redirect_to user_path(current_user)
        end
    end    
    
    private
    def album_params
        params.require(:album).permit(:title, :date, :center, :creator, :description, :nasa_id, :href, :author_id, galaxy_ids:[], galaxies_attributes: [:name, :bio, :picture_src, :size], planet_ids:[], planets_attributes: [:name, :bio, :picture_src, :size], space_obj_ids:[], space_objs_attributes: [:name, :bio, :picture_src, :size])
    end

    

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_alb.html.erb
<div class='img_row'>
<% show_albums.each do |image|%>
    <div class = 'img_col'>
    <h2>
        <%=image_tag("#{image.href}")%>
        <br>
        <div class = 'img_txt'>
        <%=link_to image.title, album_path(image)%>
        </div>
    </h2>
    </div>
<%end%>
</div>

app/views/albums/_form.html.erb
<div class='new_alb_form'>
<%= render partial:'users/errors', locals:{item: album}%>
<%= form_for(album) do |f|%>
    <%=f.hidden_field :author_id, :value => current_user.author.id%>
    <%=f.label :title, "Title"%>
    <%=f.text_field :title%>
    <br>
    <%=f.label :date, "Date"%>
    <%=f.date_field :date%>
    <br>
    <%=f.label :center, "Center(location)"%>
    <%=f.text_field :center%>
    <br>
    <%=f.label :creator, "Creator"%>
    <%=f.text_field :creator%>
    <br>
    <%=f.label :description, "Description"%>
    <%=f.text_area :description%>
    <br>
    <%=f.label :nasa_id, "Project/Nasa Id"%>
    <%=f.text_field :nasa_id%>
    <br>
    <%=f.label :href, "Picture Href"%>
    <%=f.text_field :href%>
    <br>
    <%=f.label "Select From Existing Tags"%><br>
    <%=f.label "Or create new"%>
    <%=f.label "Galaxies"%>
    <br>
    <div class = 'checkboxes'>
    <%=f.collection_check_boxes :galaxy_ids, Galaxy.all, :id, :name, :include_blank => true%>
    </div>
    <%= f.fields_for :galaxies, album.galaxies.build do |galaxies_fields| %>
        <%= galaxies_fields.text_field :name, placeholder: "Name", :include_blank => true%>
        <%= galaxies_fields.text_area :bio, placeholder: "Bio", :include_blank => true%>
        <%= galaxies_fields.text_field :picture_src, placeholder: "Picture source", :include_blank => true%>
        <%= galaxies_fields.text_field :size, placeholder: "Size", :include_blank => true%>
    <% end %>
    
    <%=f.label "Planets"%>
    <br>
    <div class = 'checkboxes'>
    <%=f.collection_check_boxes :planet_ids, Planet.all, :id, :name, :include_blank => true%>
    </div>

    <%= f.fields_for :planets, album.planets.build do |planets_fields| %>
        <%= planets_fields.text_field :name, placeholder: "Name", :include_blank => true%>
        <%= planets_fields.text_area :bio, placeholder: "Bio", :include_blank => true%>
        <%= planets_fields.text_field :picture_src, placeholder: "Picture Source", :include_blank => true%>
        <%= planets_fields.text_field :size, placeholder: "Size", :include_blank => true%>
    <% end %>
    
    <%=f.label "Space Objects"%>
    <br>
    <div class = 'checkboxes'>
    <%=f.collection_check_boxes :space_obj_ids, SpaceObj.all, :id, :name, :include_blank => true%>
    </div>
    <%= f.fields_for :space_objs, album.space_objs.build do |space_objs_fields| %>
        <%= space_objs_fields.text_field :name, placeholder: "Name", :include_blank => true%>
        <%= space_objs_fields.text_area :bio, placeholder: "Bio", :include_blank => true%>
        <%= space_objs_fields.text_field :picture_src, placeholder: "Picture Source", :include_blank => true%>
        <%= space_objs_fields.text_field :size, placeholder: "Size", :include_blank => true%>
    <% end %>
    
    <%=f.submit%>
<%end%>
</div>

app/views/albums/_related.html.erb
<% if !celestial_obj_1.empty?%>
    <h2><%= link_to "Galaxies Related to This Article", "/albums/#{album.id}/galaxies"%></h2>
    <% celestial_obj_1.each do |obj|%>
        <h3><%=link_to obj.name, galaxy_path(obj)%></h3>
        <%=image_tag("#{obj.picture_src}")%>
    <%end%>
<%end%>
<% if !celestial_obj_2.empty?%>
    <h2><%= link_to "Planets Related to This Article", "/albums/#{album.id}/planets"%></h2>
    <% celestial_obj_2.each do |obj|%>
        <h3><%=link_to obj.name, planet_path(obj)%></h3>
        <%=image_tag("#{obj.picture_src}")%>
    <%end%>
<%end%>
<% if !celestial_obj_3.empty?%>
    <h2><%= link_to "Other Objects Related to This Article", "albums/#{album.id}/space_objs"%></h2>
    <% celestial_obj_3.each do |obj|%>
        <h3><%=link_to obj.name, space_obj_path(obj)%></h3>
        <%=image_tag("#{obj.picture_src}")%>
    <%end%>
<%end%>

app/views/albums/edit.html.erb
<div class = 'container'>
<h1>Edit Album</h1>
<%=render partial:'form', locals: {album: @album}%>
</div>

app/views/albums/index.html.erb
<div class ='username_header'>
<h1>Explore</h1>
</div>
<div class='filter'>
<%= form_for :filter, :method => 'get', url: albums_path do |f| %>
    <%= f.select(:option, @filters.map {|value| [value, value]}, include_blank: true) %>
    <%= f.submit "Filter" %>
<% end %>
</div>
<%= render partial:"alb", locals: {show_albums: @albums}%>
    

app/views/albums/new.html.erb
<div class = 'container'>
<h1>Create A New Album</h1>
<%=render partial:'form', locals: {album: @album}%>
</div>

app/views/albums/show.html.erb
<div class = 'display_img'> 
    <%=image_tag("#{@album.href}")%>
    <br>
    <div class = 'display_text'>
        <h2><%=@album.title%></h2>
    </div>
    <div class='img_buttons'>
        <%if current_user.author.id == @album.author_id%>
            <%= link_to "Delete Album", "#{@album.id}/delete", data: { confirm: "Are You Sure?" }, class: 'delete_button'%>
            <%=link_to "Edit your album", edit_album_path(@album), class: 'edit_button'%>
        <%end%>
        <%=link_to "All Pictures", albums_path, class: 'explore_button'%>
    </div>

    <ul class = 'album_info'>
        <li>Date: <%=@album.date%></li>
        <li>Center: <%=@album.center%></li>
        <li>Creator: <%=@album.creator%></li>
        <br>
        <li>Description: <%=@album.description%></li>
        <li>Nasa/Project Id: <%=@album.nasa_id%></li>
    </ul>
    <div class = 'comment_container'>
        <h3>Comments:</h3>
        <% if @comments%>
            <div class = 'comment_show'>
                <ul>
                <%@comments.each do |comment|%>
                    <li><%=comment.created_time%><br>
                    <%=comment.user.name%>: <%=comment.content%>
                    <%if current_user == comment.user%>
                        <%= link_to "x", "#{@album.id}/comments/#{comment.id}", method: 'delete', data: { confirm: "Are You Sure?" }, class: 'delete_button'%>
                    <%end%></li>
                <%end%>
                </ul>
            </div>
        <%end%>
        <h4>New Comment</h4>
        <%=form_for @comment, url: comments_path, method: 'post' do |f|%>
            <%=f.hidden_field :user_id, :value => current_user.id%>
            <%=f.hidden_field :album_id, :value => @album.id%>
            <%=f.text_area :content%>
            <%=f.submit%>
        <%end%>
        <%= render partial: 'related', locals: {celestial_obj_1: @galaxies, celestial_obj_2: @planets, celestial_obj_3: @space_objs, album: @album}%>
    </div>
</div>