config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/signin', to: 'sessions#new', as: 'signin'
  post '/sessions', to: "sessions#create"
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/users/signup', to:'users#new', as:'signup'
  post '/users', to: 'users#create'
  get '/users/:id', to:'users#show', as:'user'
  get '/', to:'sessions#show'
  # get '/albums', to:'albums#index', as:'all_albums'
  post '/comments', to: 'comments#create'
  get '/albums/:id/delete', to: 'albums#destroy'
  get '/auth/facebook/callback' => 'sessions#create'
  resources :albums do 
    resources :comments
    resources :galaxies, only: [:index, :new]
  
    resources :space_objs, only: [:index, :new]
    
    resources :planets, only: [:index, :new]
  end

  resources :galaxies, only: [:show, :create] 
  
  resources :space_objs, only: [:show, :create]

  resources :planets, only: [:show, :create]

end

app/models/album.rb
class Album < ApplicationRecord
    validates :title, presence: true
    validates :date, presence: true
    validates :description, presence: true
    validates :href, presence: true
    
    belongs_to :author
    has_many :comments
    has_many :users, through: :comments
    has_many :album_planets 
    has_many :album_space_objs
    has_many :album_galaxies
    has_many :galaxies, through: :album_galaxies
    has_many :space_objs, through: :album_space_objs
    has_many :planets, through: :album_planets
    
    def self.new_albums
        @api = Api.new
        @items = @api.fetch("")
        if !@items.nil?
            @all_items = @items["collection"]["items"]
            Api.new_from_hash(@all_items, false)
        end
    end

    def self.search_albums(search)
        @api = Api.new       
        @items = @api.fetch("#{search}")
        if !@items.nil?
            @all_items = @items["collection"]["items"]
            Api.new_from_hash(@all_items, true)
        end
    end

    def self.filter_albums(filter)
        if filter[:option] == 'Most Popular'
           sorted_albums = Album.most_popular
       elsif filter[:option] == 'Newest'
           sorted_albums = Album.newest
       elsif filter[:option] == 'Oldest'
           sorted_albums = Album.oldest
       else
           return Album.all
       end
       return sorted_albums
   end

   def self.most_popular
        return Album.all.order('comments_count DESC')
   end

   def self.newest
        return Album.all.order('created_at DESC')
   end

   def self.oldest
        return Album.all.order('created_at ASC')
   end

   def galaxies_attributes=(galaxies_attributes)
    attr_status = check_if_attr_empty(galaxies_attributes)
    if attr_status == true
      galaxies_attributes.values.each do |galaxies_attribute|
        galaxy = Galaxy.find_or_create_by(galaxies_attribute)
        self.galaxies << galaxy
      end
    end
  end

  def planets_attributes=(planets_attributes)
    attr_status = check_if_attr_empty(planets_attributes)
    if attr_status == true
      planets_attributes.values.each do |planets_attribute|
        planet = Planet.find_or_create_by(planets_attribute)
        self.planets << planet
      end
    end
  end

  def space_objs_attributes=(space_objs_attributes)
    attr_status = check_if_attr_empty(space_objs_attributes)
    if attr_status == true
      space_objs_attributes.values.each do |space_objs_attribute|
        space_obj = SpaceObj.find_or_create_by(space_objs_attribute)
        self.space_objs << space_obj
      end
    end
  end

  def check_if_attr_empty(attributes)
    return true if attributes[:name] != "" && attributes[:picture_src]
  end
end

app/models/album_galaxy.rb
class AlbumGalaxy < ApplicationRecord
    belongs_to :album
    belongs_to :galaxy
end

app/models/album_planet.rb
class AlbumPlanet < ApplicationRecord
    belongs_to :album
    belongs_to :planet
end

app/models/album_solar_system.rb
class AlbumSolarSystem < ApplicationRecord
    belongs_to :album
    belongs_to :solar_system
end

app/models/album_space_obj.rb
class AlbumSpaceObj < ApplicationRecord
    belongs_to :album
    belongs_to :space_obj
end

app/models/api.rb
class Api
    def fetch(search)
        if search.empty?
            url = "https://images-api.nasa.gov/search?q=pictures"
        else
            url = "https://images-api.nasa.gov/search?q=#{search}"
        end
        response = HTTParty.get(url)
        response.parsed_response
    end  

    def self.new_from_hash(items, s)
        if s == true
            count = 0
        end
        admin = Author.find_by(id: 1)
        items.each do |i|  
            image_hash = {}
            if i["links"].present?
                image_hash["href"] = i["links"][0]["href"] 
            end
            image_hash["title"] = i["data"][0]["title"] 
            image_hash["date"] = i["data"][0]["date_created"]  
            image_hash["center"] = i["data"][0]["center"] 
            image_hash["creator"] = i["data"][0]["secondary_creator"] 
            image_hash["description"] = i["data"][0]["description"] 
            image_hash["nasa_id"] = i["data"][0]["nasa_id"]
            album = Album.new(image_hash) 
            album.author_id = admin.id
            album.save    
            if s == true
                break if count == 20
                count +=1
            end
        end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    belongs_to :user
    has_many :albums
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :album, counter_cache: true
    def created_time
        self.created_at.strftime('%H:%M %F')
    end

    def self.sort_time(comments)
        @sorted_comments = comments.sort_by{|a| a.created_at}
        @sorted_comments
    end
end

app/models/galaxy.rb
class Galaxy < ApplicationRecord
    validates :name, uniqueness: true

    has_many :album_galaxies
    has_many :albums, through: :album_galaxies
      
end

app/models/planet.rb
class Planet < ApplicationRecord
    validates :name, uniqueness: true
    has_many :album_planets
    has_many :albums, through: :album_planets
end

app/models/space_obj.rb
class SpaceObj < ApplicationRecord
    validates :name, uniqueness: true

    has_many :album_space_objs
    has_many :albums, through: :album_space_objs
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_one :author
    has_many :comments
    has_many :albums, through: :comments

    def filter_user_albums(filter)
        sorted_albums = []
        if filter == 'Created'
            sorted_albums = self.created_albums
        elsif filter == 'Commented'
            sorted_albums = self.albums
        else
        end
        return sorted_albums.uniq(&:title)
    end

    def created_albums
        return self.author.albums
    end

    def all_albums 
        albums = []
        self.albums.each do |album|
            albums << album
        end
        self.author.albums.each do |album|
            albums << album
        end
        return albums.sort_by{|album| album.created_at}.uniq(&:title)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/galaxies_helper.rb
module GalaxiesHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GalaxyScout</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if flash[:alert]%>
      <%  flash.keys.each do |type| %>
        <div class='alert'>
        <div data-alert class="flash <%= type %> alert-box radius">
          <%= flash[type] %>
          <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        </div>
      <% end %>

    <%end%>
  </div>
  <div class = 'header'>
    <%=image_tag("homepag.jpg")%>
    <div class = 'header_text'>
      <h1><i class = 'fa fa-rocket'></i> Galaxy Scout</h1>
    </div>
  </div>
  <br>
  <div class='icon-bar'>
      <%if session[:user_id]%>
        <a class ="active" href=<%=albums_path%>><i class = "fa fa-home"></i></a>
        <a href=<%=user_path(current_user)%>><i class="fa fa-user-circle"></i></a>
        <a href=<%=new_album_path%>><i class="fa fa-plus-circle"></i></a>
        <a><i class='fa fa-search'>
        <%if current_page?(user_path(current_user))%>
          <%=form_tag user_path(current_user), method: "get" do%>
            <%=text_field_tag "search"%>
            <%=submit_tag "Search User Albums", :style => "display: none;"%>
          <%end%>
        <%else%>
          <%=form_tag albums_path, method: "get" do%>
            <%=text_field_tag "search"%>
            <%=submit_tag "Search Database", :style => "display: none;"%>
          <%end%>
        <%end%>
        </i></a>
        <a href=<%=logout_path%>><i class ="fa fa-user-times"></i></a>
      <%else%>
        <a href='/'><i class ="fa fa-home"></i></a>
        <a href=<%=signin_path%>><i class ="fa fa-user-circle"></i></a>
        <a href=<%=signup_path%>><i class="fa fa-vcard"></i></a>
      <%end%>
  </div>



  <div class = 'content'>
    <%= yield %>
  </div>
  </body>
  <footer>
  </footer>
</html>